add deletet and update post function
zamukaev/capstone-project pull request #18
Opened 2023-04-13 13:14 UTC by zamukaev

2023-04-13 14:23 UTC, toshydev requested changes
Code looks good to me but I can't approve the PR because the delete and edit buttons are not shown.
I see you're using an `.env` file. Did you upload it to vercel?

2023-04-14 10:16 UTC, PReichetanz reviewed
Good work, just an idea and questions from my side.

2023-04-14 10:16 UTC, PReichetanz commented on components/CreateNewPost/index.jsx
> +const CreateNewPost = ({ post, isEdit, setIsEdit }) => {
I suggest to call the state `isEditing` to mark the process; by doing so, `isEditing ? ...` does make more sense than `isEdit ? ...`.

Besides, we normally don't pass the setter function directly, but wrap it into a `handleIsEditing` (or similar` and pass this wrapper as `onHandleIsEditing` prop.

2023-04-14 10:16 UTC, PReichetanz commented on components/CreateNewPost/index.jsx
> +      const { data } = isEdit
I don't understand this: why do you destructure `data` from `isEdit` and how does the ternary work here?

2023-04-14 10:16 UTC, PReichetanz commented on components/CreateNewPost/index.jsx
> +      setIsEdit && setIsEdit(!isEdit);
I'm not sure about this: since `setIsEdit` is a function, it does not make sense to me to check whether it's truthy and only then (`&&`)  call `setIsEdit`. Why should `setIsEdit` not be there if it is passed as a prop?

2023-04-14 10:16 UTC, PReichetanz commented on pages/posts/[id].jsx
> +  const [isEdit, setIsEdit] = useState(false);
```suggestion
  const [isEditing, setIsEditing] = useState(false);
```

2023-04-14 18:21 UTC, toshydev approved these changes
I added a suggestion but apart from that everything LGTM! 🚀

2023-04-14 18:21 UTC, toshydev commented on components/CreateNewPost/index.jsx
> +      onHandleIsEditing && onHandleIsEditing();
Why are you checking if `onHandleIsEditing` is true? You could just call the function since you're passing it as a prop anyway.
```suggestion
      onHandleIsEditing();
```

2023-04-15 16:57 UTC, merged