Feature/home
zamukaev/capstone-project pull request #9
Opened 2023-03-28 12:50 UTC by zamukaev

2023-03-29 07:29 UTC, PReichetanz reviewed
Nice work! I left some comments to discuss.

Please note that many coaches cannot support TypeScript. I will speak with Thomas and the team how we can handle this.

2023-03-29 07:29 UTC, PReichetanz commented on components/Headline/Headline.ts
> +// styled h tag
I don't think that you will need this comment ;)

2023-03-29 07:29 UTC, PReichetanz commented on components/Headline/HeadlineProps.ts
> +}
Please note that you won't get any support for any TypeScript related code.

2023-03-29 07:29 UTC, PReichetanz commented on components/PTag/PTag.test.tsx
> +  render(<PTag>i like this work</PTag>);
You don't need to test a simple styled component, because it's only a HTML `p` element.

2023-03-29 07:29 UTC, PReichetanz commented on components/Posts/index.test.tsx
> +  expect(screen.getByAltText(/photo of post/i));
Can you use `getByRole` here? Maybe reconsider the usage of more semantic HTML elements.

2023-03-29 07:29 UTC, PReichetanz commented on components/Posts/index.tsx
> +            <PTag>{post.content}</PTag>
I would rather use something like `StyledParagraph` to be more descriptive.

2023-03-29 07:29 UTC, PReichetanz commented on db/models/posts.ts
> +interface IPost {
What does `IPost` mean here? Could you be more descriptive regarding the naming?

2023-03-29 07:29 UTC, PReichetanz commented on next-env.d.ts
> +// see https://nextjs.org/docs/basic-features/typescript for more information.
Please remove unused comments.

2023-03-29 07:29 UTC, PReichetanz commented on pages/api/posts/index.ts
> +  }
You could add an option of the `request.method` is not known or allowed (refer to the handout).

2023-03-29 07:29 UTC, PReichetanz commented on styles.ts
> +    border:0;
Looks like the prettier extension of VSCode does not format on save; please check the config.

2023-03-29 15:07 UTC, PReichetanz reviewed
Nice work!

2023-03-29 15:07 UTC, PReichetanz commented on package.json
> +    "ts-node": "^10.9.1"
I'm curious: What is this for?

2023-03-29 15:07 UTC, PReichetanz commented on styles.js
> +h6{
Still looks like prettier is not working (there should be a whitespace between the 6 and the curly brace). Check your VSCode config.

2023-03-29 15:40 UTC, zamukaev commented on styles.js
> +h6{
I don't now why, but it is not working

2023-03-29 15:52 UTC, zamukaev commented on components/Posts/index.test.js
> +});
but by paragraph it doesn't work

2023-03-29 17:17 UTC, zamukaev commented on styles.js
> +h6{
it's working but not in global styles

2023-03-30 09:22 UTC, PReichetanz requested changes
Good rework: only one remark regarding file naming and one recommendation to use lists and list items when mapping over an array to be accessible.

2023-03-30 09:22 UTC, PReichetanz commented on components/Posts/Posts.styles.js
> +import styled from "styled-components";
The file name for styled components should rather be `Posts.styled.js`; however, this is rather opinionated, so if you rename them and everything else is fine, you don't need another code review.

2023-03-30 09:22 UTC, PReichetanz commented on components/Posts/index.jsx
> +      {posts.map((post) => (
To be accessible, we recommend to use lists and list items for every item created by `.map()`.

2023-03-30 13:12 UTC, merged